### ISSUE TITLE
Shamans - Banking sometimes gets stuck on Enter Amount dialog

### ISSUE THREAD

**Issue by alexfaxe** [squire-plugins/bugs#16]
most likely related to banking speed vs ping

**Comment by gargslayer101** [comment]
Possible duplicate of https://gitlab.com/runemate/community/runemate-client/-/issues/209

**Comment by chadsisson** [comment]
https://github.com/squire-plugins/SquirePlugins/commit/16d93bbd422779abacf7a2e44dc62561b23c30ea
