### ISSUE TITLE
[low priority] Chaos Altar Plugin Missing from wiki's list

### ISSUE THREAD

**Issue by zmike808** [squire-plugins/bugs#27]
https://github.com/squire-plugins/bugs/wiki/Helper-Plugins 
Doesn't list the "Squire Chaos Altar" plugin, which IMO is one of the best plugins included in base squire. Would be a smart idea to add that and a small description. And personally, I'd add a recommendation/mention of how comboing it with AutoLogHop by Sox makes it even more absurd/100% automated instead of 95% (remaining 5% is picking worlds until you find a empty one)

**Comment by alexfaxe** [comment]
done
